### ISSUE TITLE
jupyter notebook reconstruct_measured_data: missing file 20170809_NEMA_60min_UCL.l.hdr

### ISSUE THREAD

**Issue by evgueni-ovtchinnikov** [CCPPETMR/SIRF-Exercises#11]
In [2]:
list.l                  mMR_template_span11.s         mu_map.hv  norm.n.hdr
list.l.hdr              mMR_template_span11_small.hs  mu_map.v   README.md
mMR_template_span11.hs  mMR_template_span11_small.s   norm.n

In [7]:
error: ??? "'Error opening file 20170809_NEMA_60min_UCL.l.hdr\\n' exception caught at line 261 of /home/sirfuser/devel/buildVM/sources/SIRF/src/xSTIR/cSTIR/cstir.cpp\nthe reconstruction engine output may provide more information"

**Comment by KrisThielemans** [comment]
should be fine after doing the download described in https://github.com/CCPPETMR/SIRF-Exercises/blob/master/INSTALL.md.
