### ISSUE TITLE
old MR notebooks have multiple problems

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF-Exercises#29]
The older notebooks (not those in the interactive folder) were stripped too much and we get an error when opening them (see the process in #20).

They also need changing of `petmr_data_path(...)` with `examples_data_path('MR')`.

However, I suspect that the notebooks in https://github.com/CCPPETMR/SIRF-Exercises/tree/master/notebooks/MR shouldn't really be there anymore and are superseded by those in [interactive](https://github.com/CCPPETMR/SIRF-Exercises/tree/master/notebooks/MR/interactive). @ckolbPTB @johannesmayer @DANAJK could you confirm that these are safe too delete?

I'm not sure what to do with those in [tools](https://github.com/CCPPETMR/SIRF-Exercises/tree/master/notebooks/MR/tools). [acqh5info](https://github.com/CCPPETMR/SIRF-Exercises/blob/master/notebooks/MR/tools/acqh5info.ipynb)  might contain things that are now elsewhere.  [im5info](https://github.com/CCPPETMR/SIRF-Exercises/blob/master/notebooks/MR/tools/im5info.ipynb) uses `h5py` and seems interesting (but could do with some more info). @DANAJK, do we keep these ?

**Comment by paskino** [comment]
I was in the process of testing the notebooks. 
I fixed the notebooks in `MR` https://github.com/CCPPETMR/SIRF-Exercises/pull/30

Except from [this](https://github.com/CCPPETMR/SIRF-Exercises/blob/master/notebooks/MR/Gadgetron/fully_sampled_recon_three_chains.ipynb) the others seem to work.

**Comment by KrisThielemans** [comment]
what's the problem with the remaining one?

**Comment by KrisThielemans** [comment]
I've created a separate issue for the remaining problem. https://github.com/CCPPETMR/SIRF-Exercises/issues/31
