### ISSUE TITLE
Change URLs for MR data

### ISSUE THREAD

**Issue by bathomas** [CCPPETMR/SIRF-Exercises#33]
Both:

https://github.com/CCPPETMR/SIRF-Exercises/blob/2e52fb8071bb401bdb113a6b542474d9e717b091/scripts/download_MR_data.sh#L49

and 

https://github.com/CCPPETMR/SIRF-Exercises/blob/2e52fb8071bb401bdb113a6b542474d9e717b091/scripts/download_MR_data.sh#L57

should be changed to not rely on DropBox.

**Comment by bathomas** [comment]
What seems like throttling from Dropbox slows/stops machine builds for Azure.

**Comment by KrisThielemans** [comment]
closing as this is now only for the "old" notebooks which we're normally not using
