### ISSUE TITLE
change URL for NEMA data

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF-Exercises#8]
the current azure link will expire afer the course so we need to put the data elsewhere later on.

**Comment by paskino** [comment]
Uploading to the ccppetmr website would do?

**Comment by KrisThielemans** [comment]
sure, but don't do it now! We need to get moving on uploading to zenodo but that requires better preparation..

**Comment by KrisThielemans** [comment]
was fixed ages ago
